import { Photo, GallerySection } from '@/types';

// Cinematic color palettes for placeholders
const PALETTES = {
  midnight: ['#0a0d12', '#0c1018', '#080b10', '#0e121a'],
  dusk:     ['#1a1208', '#140e05', '#1c1409', '#100c04'],
  forest:   ['#080d0a', '#060b08', '#0a0f0c', '#04080600'],
  ash:      ['#0f0f0f', '#111111', '#0d0d0d', '#131313'],
  indigo:   ['#0a0b14', '#0c0e1a', '#080912', '#0e1020'],
  ember:    ['#150804', '#120604', '#180a05', '#100603'],
};

function p(category: keyof typeof PALETTES, idx: number) {
  const pal = PALETTES[category];
  return pal[idx % pal.length];
}

export const featuredPhotos: Photo[] = [
  {
    id: 'f1',
    title: 'Threshold',
    subtitle: 'Where light becomes memory',
    description: 'A study in negative space and the geometry of abandonment.',
    src: '',
    placeholder: p('midnight', 0),
    width: 2400,
    height: 3200,
    category: 'projects',
    featured: true,
    featured_order: 1,
    metadata: {
      camera: 'Leica M6',
      lens: '35mm Summicron',
      aperture: 'f/2.0',
      shutter: '1/125',
      iso: '400',
      location: 'Tokyo, Japan',
      date: 'March 2024',
      thoughts: 'Shot at 5am when the city held its breath.',
    },
  },
  {
    id: 'f2',
    title: 'Fugue State',
    subtitle: 'Motion as emotion',
    description: 'Long exposure abstractions from moving bodies of water.',
    src: '',
    placeholder: p('dusk', 1),
    width: 3200,
    height: 2400,
    category: 'experimental',
    featured: true,
    featured_order: 2,
    metadata: {
      camera: 'Hasselblad 500CM',
      lens: '80mm Planar',
      aperture: 'f/8.0',
      shutter: '4s',
      iso: '100',
      location: 'Iceland',
      date: 'November 2023',
      thoughts: 'The water knew something we did not.',
    },
  },
  {
    id: 'f3',
    title: 'Negative Space',
    subtitle: 'The silence between things',
    description: 'Architecture reduced to essential geometry.',
    src: '',
    placeholder: p('ash', 0),
    width: 2400,
    height: 2400,
    category: 'bw',
    featured: true,
    featured_order: 3,
    metadata: {
      camera: 'Nikon F3',
      lens: '28mm Nikkor',
      aperture: 'f/11',
      shutter: '1/250',
      iso: '400',
      location: 'Berlin, Germany',
      date: 'January 2024',
      thoughts: 'Brutalism as poetry. The void speaks.',
    },
  },
];

export const projectPhotos: Photo[] = [
  {
    id: 'p1',
    title: 'Threshold',
    src: '',
    placeholder: p('midnight', 0),
    width: 2400,
    height: 3200,
    category: 'projects',
    featured: true,
    metadata: { camera: 'Leica M6', lens: '35mm', aperture: 'f/2.0', location: 'Tokyo', date: 'Mar 2024' },
  },
  {
    id: 'p2',
    title: 'Corridor',
    src: '',
    placeholder: p('indigo', 1),
    width: 3200,
    height: 2100,
    category: 'projects',
    metadata: { camera: 'Leica M6', lens: '50mm', aperture: 'f/1.4', location: 'Osaka', date: 'Mar 2024' },
  },
  {
    id: 'p3',
    title: 'Interval',
    src: '',
    placeholder: p('midnight', 2),
    width: 2400,
    height: 3600,
    category: 'projects',
    metadata: { camera: 'Contax G2', lens: '45mm', aperture: 'f/2.8', location: 'Kyoto', date: 'Apr 2024' },
  },
  {
    id: 'p4',
    title: 'Signal',
    src: '',
    placeholder: p('dusk', 0),
    width: 3600,
    height: 2400,
    category: 'projects',
    metadata: { camera: 'Leica M6', lens: '35mm', aperture: 'f/4', location: 'Tokyo', date: 'Mar 2024' },
  },
  {
    id: 'p5',
    title: 'Dissolve',
    src: '',
    placeholder: p('indigo', 2),
    width: 2700,
    height: 3600,
    category: 'projects',
    metadata: { camera: 'Nikon F3', lens: '85mm', aperture: 'f/2', location: 'Tokyo', date: 'Feb 2024' },
  },
  {
    id: 'p6',
    title: 'Periphery',
    src: '',
    placeholder: p('midnight', 1),
    width: 3200,
    height: 2400,
    category: 'projects',
    metadata: { camera: 'Leica M6', lens: '28mm', aperture: 'f/5.6', location: 'Yokohama', date: 'Mar 2024' },
  },
  {
    id: 'p7',
    title: 'Residue',
    src: '',
    placeholder: p('ember', 0),
    width: 2400,
    height: 3600,
    category: 'projects',
    metadata: { camera: 'Leica M6', lens: '35mm', aperture: 'f/2', location: 'Hiroshima', date: 'Apr 2024' },
  },
  {
    id: 'p8',
    title: 'Flux',
    src: '',
    placeholder: p('indigo', 0),
    width: 3600,
    height: 2700,
    category: 'projects',
    metadata: { camera: 'Contax G2', lens: '28mm', aperture: 'f/3.5', location: 'Tokyo', date: 'May 2024' },
  },
];

export const experimentalPhotos: Photo[] = [
  {
    id: 'e1',
    title: 'Fugue State',
    src: '',
    placeholder: p('dusk', 1),
    width: 3200,
    height: 2400,
    category: 'experimental',
    featured: true,
    metadata: { camera: 'Hasselblad 500CM', lens: '80mm', aperture: 'f/8', shutter: '4s', location: 'Iceland', date: 'Nov 2023' },
  },
  {
    id: 'e2',
    title: 'Double Exposure I',
    src: '',
    placeholder: p('forest', 0),
    width: 2400,
    height: 2400,
    category: 'experimental',
    metadata: { camera: 'Holga 120N', lens: 'Stock 60mm', aperture: 'f/8', location: 'London', date: 'Sep 2023' },
  },
  {
    id: 'e3',
    title: 'Chemigram No. 7',
    src: '',
    placeholder: p('ember', 1),
    width: 2400,
    height: 3000,
    category: 'experimental',
    metadata: { camera: 'Darkroom Process', location: 'Studio', date: 'Dec 2023', thoughts: 'Developer as brush. Fixer as memory.' },
  },
  {
    id: 'e4',
    title: 'Solarized',
    src: '',
    placeholder: p('dusk', 2),
    width: 3600,
    height: 2400,
    category: 'experimental',
    metadata: { camera: 'Rolleiflex 3.5F', lens: '75mm Planar', aperture: 'f/5.6', location: 'New York', date: 'Jan 2024' },
  },
  {
    id: 'e5',
    title: 'Pinhole Study',
    src: '',
    placeholder: p('forest', 2),
    width: 2400,
    height: 2400,
    category: 'experimental',
    metadata: { camera: 'Zero Image 4x5', shutter: '45s', location: 'Arizona', date: 'Feb 2024', thoughts: 'Time made visible.' },
  },
  {
    id: 'e6',
    title: 'Expired Film',
    src: '',
    placeholder: p('ember', 2),
    width: 2700,
    height: 3600,
    category: 'experimental',
    metadata: { camera: 'Nikon FM2', lens: '50mm', location: 'Various', date: '2023–2024', thoughts: 'Fuji Velvia from 1998.' },
  },
];

export const bwPhotos: Photo[] = [
  {
    id: 'b1',
    title: 'Negative Space',
    src: '',
    placeholder: p('ash', 0),
    width: 2400,
    height: 2400,
    category: 'bw',
    featured: true,
    metadata: { camera: 'Nikon F3', lens: '28mm', aperture: 'f/11', location: 'Berlin', date: 'Jan 2024' },
  },
  {
    id: 'b2',
    title: 'Chiaroscuro',
    src: '',
    placeholder: p('ash', 1),
    width: 2400,
    height: 3600,
    category: 'bw',
    metadata: { camera: 'Leica M6', lens: '50mm Summilux', aperture: 'f/1.4', iso: '3200', location: 'Paris', date: 'Dec 2023' },
  },
  {
    id: 'b3',
    title: 'Grain Study',
    src: '',
    placeholder: p('ash', 2),
    width: 3600,
    height: 2400,
    category: 'bw',
    metadata: { camera: 'Nikon F3', lens: '85mm', iso: '6400', location: 'Chicago', date: 'Nov 2023', thoughts: 'Pushed Kodak Tri-X 3 stops.' },
  },
  {
    id: 'b4',
    title: 'Geometry I',
    src: '',
    placeholder: p('ash', 3),
    width: 2400,
    height: 3000,
    category: 'bw',
    metadata: { camera: 'Hasselblad 500CM', lens: '50mm', location: 'Chicago', date: 'Oct 2023' },
  },
  {
    id: 'b5',
    title: 'Rain',
    src: '',
    placeholder: '#0a0a0a',
    width: 3200,
    height: 2400,
    category: 'bw',
    metadata: { camera: 'Leica M6', lens: '35mm', aperture: 'f/2', iso: '800', location: 'Seoul', date: 'Sep 2023' },
  },
  {
    id: 'b6',
    title: 'Interior',
    src: '',
    placeholder: '#111111',
    width: 2700,
    height: 3600,
    category: 'bw',
    metadata: { camera: 'Rolleiflex 3.5F', lens: '75mm', location: 'Havana', date: 'Aug 2023' },
  },
  {
    id: 'b7',
    title: 'Portrait of Absence',
    src: '',
    placeholder: '#0d0d0d',
    width: 2400,
    height: 3600,
    category: 'bw',
    metadata: { camera: 'Leica M6', lens: '90mm Elmarit', aperture: 'f/2.8', location: 'New York', date: 'Jul 2023' },
  },
  {
    id: 'b8',
    title: 'Meridian',
    src: '',
    placeholder: '#131313',
    width: 3600,
    height: 2400,
    category: 'bw',
    metadata: { camera: 'Nikon F3', lens: '20mm', location: 'Death Valley', date: 'Jun 2023' },
  },
];

export const essayPhotos: Photo[] = [
  {
    id: 'es1',
    title: 'On Waiting',
    subtitle: 'A visual essay on liminal time',
    description: 'Eleven photographs made in transit spaces — airports, train platforms, ferry terminals. An exploration of the time we inhabit between places.',
    src: '',
    placeholder: p('midnight', 3),
    width: 3200,
    height: 2100,
    category: 'essays',
    featured: true,
    essay: {
      title: 'On Waiting',
      intro: 'Every journey is mostly waiting. The photographs here were made in the margins — the hours before departure, the silence of arrivals. I wanted to find what happens to a face, a posture, a room, when time slows to its most elastic.',
      sections: [
        { heading: 'I.', body: 'The fluorescent light of a departure gate at 4am is unlike any other light. It flattens everything equally — the anxious executive, the returning student, the couple who has said everything.' },
        { heading: 'II.', body: 'I have always been interested in what people do with their hands when they think no one is watching. In waiting rooms, the guard drops. The hands tell the truth.' },
        { heading: 'III.', body: 'These eleven photographs were made over fourteen months across nine countries. The only constraint I gave myself: no staged images. Everything here happened before my camera found it.' },
      ],
    },
    metadata: { camera: 'Various', date: '2022–2024', thoughts: '14 months, 9 countries, 47 rolls of film.' },
  },
  {
    id: 'es2',
    title: 'Light Pollution',
    subtitle: 'The sky we lost',
    description: 'A meditation on artificial light and the stars we can no longer see.',
    src: '',
    placeholder: p('indigo', 3),
    width: 2400,
    height: 3200,
    category: 'essays',
    essay: {
      title: 'Light Pollution',
      intro: 'In 1994, after an earthquake knocked out power across Los Angeles, thousands of residents called emergency services to report a strange silvery cloud overhead. It was the Milky Way.',
      sections: [
        { heading: 'I.', body: 'I drove six hours into the Mojave to see something my grandparents could see from their front porch.' },
        { heading: 'II.', body: 'The camera sees more than the eye. A four-minute exposure in a truly dark sky produces something approaching religious experience.' },
      ],
    },
    metadata: { camera: 'Nikon F3', lens: '20mm', location: 'Mojave & various', date: '2023' },
  },
  {
    id: 'es3',
    title: 'The Demolition Series',
    subtitle: 'Before the erasure',
    description: 'Documenting buildings in their final weeks before demolition across three cities.',
    src: '',
    placeholder: p('ember', 3),
    width: 2700,
    height: 3600,
    category: 'essays',
    essay: {
      title: 'The Demolition Series',
      intro: 'I started photographing buildings scheduled for demolition after I missed the last chance to photograph a theater I had loved since childhood.',
      sections: [
        { heading: 'I.', body: 'There is a quality of light in an abandoned building that exists nowhere else. The dust. The stillness. The sense that the space itself is bracing for the end.' },
        { heading: 'II.', body: 'I always tried to photograph during the magic hour, when the low light streamed through windows that would soon be rubble.' },
      ],
    },
    metadata: { camera: 'Hasselblad 500CM', lens: '50mm', location: 'Detroit, Chicago, Baltimore', date: '2022–2023' },
  },
];

// All photos combined
export const allPhotos: Photo[] = [
  ...projectPhotos,
  ...experimentalPhotos,
  ...bwPhotos,
  ...essayPhotos,
];

// Gallery sections for the homepage
export const gallerySections: GallerySection[] = [
  {
    id: 'projects',
    title: 'Projects',
    subtitle: 'Long-form documentary work',
    description: 'Multi-image narratives exploring place, time, and human presence.',
    photos: projectPhotos,
    layout: 'masonry',
  },
  {
    id: 'experimental',
    title: 'Experimental',
    subtitle: 'Process and abstraction',
    description: 'Alternative processes, multiple exposures, and chemical experimentation.',
    photos: experimentalPhotos,
    layout: 'grid',
  },
  {
    id: 'bw',
    title: 'Black & White',
    subtitle: 'The classical form',
    description: 'Silver gelatin aesthetics in the tradition of documentary photography.',
    photos: bwPhotos,
    layout: 'masonry',
  },
  {
    id: 'essays',
    title: 'Visual Essays',
    subtitle: 'Photography as literature',
    description: 'Sequences of images that tell extended stories.',
    photos: essayPhotos,
    layout: 'editorial',
  },
];

export function getPhotoById(id: string): Photo | undefined {
  return allPhotos.find(p => p.id === id);
}

export function getPhotosByCategory(category: Photo['category']): Photo[] {
  return allPhotos.filter(p => p.category === category);
}

export function getFeaturedPhotos(): Photo[] {
  return allPhotos.filter(p => p.featured).sort((a, b) => (a.featured_order ?? 99) - (b.featured_order ?? 99));
}
